runtime: python
env: flex
entrypoint: gunicorn -b :$PORT -k eventlet -w 1 app:app  # Uses eventlet for SocketIO
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "3.11"
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
env_variables:
  ADMIN_PASSWORD: "Braj2025"